import { Hono } from 'hono';
import { z } from 'zod';
import { createPrisma } from '../lib/worker-prisma';
import { authenticate, requireRoles, type WorkerRouteEnv } from './shared';

const rewards = new Hono<WorkerRouteEnv>();
async function familyId(url: string, userId: string) { const db=createPrisma(url); try{return (await db.familyMember.findFirst({where:{userId}}))?.familyId??null}finally{await db.$disconnect()} }
rewards.get('/',authenticate,async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const fid=await familyId(c.env.DATABASE_URL,c.get('user').userId);if(!fid)return c.json({rewards:[]});const rewards=await db.reward.findMany({where:{familyId:fid,isActive:true},orderBy:{cost:'asc'}});return c.json({rewards})}catch(e){console.error(e);return c.json({error:'取得獎勵失敗'},500)}finally{await db.$disconnect()}});
rewards.post('/',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({title:z.string().min(1),description:z.string().optional(),cost:z.number().int().positive()}).safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const fid=await familyId(c.env.DATABASE_URL,c.get('user').userId);if(!fid)return c.json({error:'請先建立或加入家庭'},400);const reward=await db.reward.create({data:{familyId:fid,createdById:c.get('user').userId,...p.data}});return c.json({reward},201)}catch(e){console.error(e);return c.json({error:'建立獎勵失敗'},500)}finally{await db.$disconnect()}});
rewards.post('/:id/redeem',authenticate,async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const reward=await db.reward.findUnique({where:{id:c.req.param('id')}});if(!reward||!reward.isActive)return c.json({error:'獎勵不存在'},404);const userId=c.get('user').userId;if(await familyId(c.env.DATABASE_URL,userId)!==reward.familyId)return c.json({error:'無權兌換此獎勵'},403);const user=await db.user.findUnique({where:{id:userId}});if(!user||user.points<reward.cost)return c.json({error:'積分不足'},400);if(await db.rewardRedemption.findFirst({where:{rewardId:reward.id,userId,status:'PENDING'}}))return c.json({error:'已有待審核的兌換申請'},400);const redemption=await db.rewardRedemption.create({data:{rewardId:reward.id,userId}});return c.json({redemption},201)}catch(e){console.error(e);return c.json({error:'兌換失敗'},500)}finally{await db.$disconnect()}});
rewards.put('/redemptions/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({status:z.enum(['APPROVED','REJECTED'])}).safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const x=await db.rewardRedemption.findUnique({where:{id:c.req.param('id')},include:{reward:true}});if(!x||x.status!=='PENDING')return c.json({error:'找不到待審核的兌換'},404);if(await familyId(c.env.DATABASE_URL,c.get('user').userId)!==x.reward.familyId)return c.json({error:'無權審核'},403);const redemption=await db.$transaction(async tx=>{if(p.data.status==='APPROVED'){const u=await tx.user.findUnique({where:{id:x.userId}});if(!u||u.points<x.reward.cost)throw new Error('INTEGRAL_INSUFFICIENT');await tx.user.update({where:{id:x.userId},data:{points:{decrement:x.reward.cost}}});await tx.pointTransaction.create({data:{userId:x.userId,amount:-x.reward.cost,type:'SPEND',reason:`兌換獎勵：${x.reward.title}`,createdBy:c.get('user').userId}})}return tx.rewardRedemption.update({where:{id:x.id},data:{status:p.data.status,reviewedAt:new Date(),reviewedBy:c.get('user').userId}})});return c.json({redemption})}catch(e){console.error(e);return c.json({error:e instanceof Error&&e.message==='INTEGRAL_INSUFFICIENT'?'孩子積分不足，無法核准':'審核失敗'},e instanceof Error&&e.message==='INTEGRAL_INSUFFICIENT'?400:500)}finally{await db.$disconnect()}});
rewards.get('/pending',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const fid=await familyId(c.env.DATABASE_URL,c.get('user').userId);if(!fid)return c.json({redemptions:[]});const redemptions=await db.rewardRedemption.findMany({where:{status:'PENDING',reward:{familyId:fid}},include:{reward:true,user:{select:{id:true,name:true,points:true}}},orderBy:{createdAt:'desc'}});return c.json({redemptions})}catch(e){console.error(e);return c.json({error:'取得待審核兌換失敗'},500)}finally{await db.$disconnect()}});
rewards.put('/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({title:z.string().min(1).optional(),description:z.string().nullable().optional(),cost:z.number().int().positive().optional()}).safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const reward=await db.reward.findUnique({where:{id:c.req.param('id')}});if(!reward)return c.json({error:'獎勵不存在'},404);if(await familyId(c.env.DATABASE_URL,c.get('user').userId)!==reward.familyId)return c.json({error:'無權編輯此獎勵'},403);const updated=await db.reward.update({where:{id:reward.id},data:p.data});return c.json({reward:updated})}catch(e){console.error(e);return c.json({error:'更新獎勵失敗'},500)}finally{await db.$disconnect()}});
rewards.delete('/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const reward=await db.reward.findUnique({where:{id:c.req.param('id')}});if(!reward)return c.json({error:'獎勵不存在'},404);if(await familyId(c.env.DATABASE_URL,c.get('user').userId)!==reward.familyId)return c.json({error:'無權刪除此獎勵'},403);const count=await db.rewardRedemption.count({where:{rewardId:reward.id}});if(count>0){const archived=await db.reward.update({where:{id:reward.id},data:{isActive:false}});return c.json({success:true,archived:true,reward:archived})}await db.reward.delete({where:{id:reward.id}});return c.json({success:true,archived:false})}catch(e){console.error(e);return c.json({error:'刪除獎勵失敗'},500)}finally{await db.$disconnect()}});
export default rewards;
