import { Hono } from 'hono';
import { z } from 'zod';
import { createPrisma } from '../lib/worker-prisma';
import { authenticate, requireRoles, type WorkerRouteEnv } from './shared';

const scheduledAwards = new Hono<WorkerRouteEnv>();
const input = z.object({ userId:z.string().min(1), name:z.string().min(1).max(100), amount:z.number().int().positive(), frequency:z.enum(['daily','weekly','monthly']), startAt:z.string().datetime().optional(), isActive:z.boolean().optional() });
async function familyId(url:string,userId:string){const db=createPrisma(url);try{return(await db.familyMember.findFirst({where:{userId}}))?.familyId??null}finally{await db.$disconnect()}}

scheduledAwards.get('/', authenticate, requireRoles('PARENT','ADMIN'), async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const f=await familyId(c.env.DATABASE_URL,c.get('user').userId);if(!f)return c.json({schedules:[]});const schedules=await db.scheduledAward.findMany({where:{familyId:f},orderBy:{createdAt:'desc'}});const users=await db.user.findMany({where:{id:{in:schedules.map(s=>s.userId)}},select:{id:true,name:true}});return c.json({schedules:schedules.map(s=>({...s,user:users.find(u=>u.id===s.userId)}))})}finally{await db.$disconnect()}});
scheduledAwards.post('/', authenticate, requireRoles('PARENT','ADMIN'), async c=>{const p=input.safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const f=await familyId(c.env.DATABASE_URL,c.get('user').userId);if(!f||!await db.familyMember.findFirst({where:{familyId:f,userId:p.data.userId}}))return c.json({error:'目標成員不在家庭中'},400);return c.json({schedule:await db.scheduledAward.create({data:{...p.data,familyId:f,createdById:c.get('user').userId,startAt:p.data.startAt?new Date(p.data.startAt):new Date()}})},201)}finally{await db.$disconnect()}});
scheduledAwards.put('/:id', authenticate, requireRoles('PARENT','ADMIN'), async c=>{const p=input.partial().safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const f=await familyId(c.env.DATABASE_URL,c.get('user').userId);const schedule=await db.scheduledAward.findFirst({where:{id:c.req.param('id'),familyId:f??undefined}});if(!schedule)return c.json({error:'找不到設定'},404);return c.json({schedule:await db.scheduledAward.update({where:{id:schedule.id},data:{...p.data,startAt:p.data.startAt?new Date(p.data.startAt):undefined}})})}finally{await db.$disconnect()}});
scheduledAwards.delete('/:id', authenticate, requireRoles('PARENT','ADMIN'), async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const f=await familyId(c.env.DATABASE_URL,c.get('user').userId);const schedule=await db.scheduledAward.findFirst({where:{id:c.req.param('id'),familyId:f??undefined}});if(!schedule)return c.json({error:'找不到設定'},404);await db.scheduledAward.delete({where:{id:schedule.id}});return c.json({success:true})}finally{await db.$disconnect()}});
export default scheduledAwards;
