import { Hono } from 'hono';
import { z } from 'zod';
import { createPrisma } from '../lib/worker-prisma';
import { evaluateTrophies } from '../lib/trophies';
import { authenticate, requireRoles, type WorkerRouteEnv } from './shared';
const tasks=new Hono<WorkerRouteEnv>();
const input=z.object({title:z.string().min(1),description:z.string().optional(),points:z.number().int().positive(),isRecurring:z.boolean().optional(),recurringType:z.enum(['daily','weekly']).optional(),keepAfterCompletion:z.boolean().optional(),maxCompletions:z.number().int().positive().nullable().optional(),groupId:z.string().nullable().optional()});
async function family(url:string,id:string){const db=createPrisma(url);try{return(await db.familyMember.findFirst({where:{userId:id}}))?.familyId??null}finally{await db.$disconnect()}}
async function groupOk(url:string,f:string,g:string|null|undefined){if(!g)return true;const db=createPrisma(url);try{return!!await db.taskGroup.findFirst({where:{id:g,familyId:f}})}finally{await db.$disconnect()}}
tasks.get('/groups',authenticate,async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const f=await family(c.env.DATABASE_URL,c.get('user').userId);return c.json({groups:f?await db.taskGroup.findMany({where:{familyId:f},orderBy:{sortOrder:'asc'}}):[]})}finally{await db.$disconnect()}});
tasks.post('/groups',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({name:z.string().min(1).max(50)}).safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const f=await family(c.env.DATABASE_URL,c.get('user').userId);if(!f)return c.json({error:'請先建立或加入家庭'},400);const m=await db.taskGroup.aggregate({where:{familyId:f},_max:{sortOrder:true}});return c.json({group:await db.taskGroup.create({data:{familyId:f,name:p.data.name.trim(),sortOrder:(m._max.sortOrder??-1)+1}})},201)}catch{return c.json({error:'建立群組失敗；名稱可能重複'},400)}finally{await db.$disconnect()}});
tasks.put('/groups/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({name:z.string().min(1).max(50)}).safeParse(await c.req.json());const db=createPrisma(c.env.DATABASE_URL);try{const f=await family(c.env.DATABASE_URL,c.get('user').userId);const g=await db.taskGroup.findFirst({where:{id:c.req.param('id'),familyId:f??undefined}});if(!p.success||!g)return c.json({error:'群組不存在或名稱無效'},400);return c.json({group:await db.taskGroup.update({where:{id:g.id},data:{name:p.data.name.trim()}})})}finally{await db.$disconnect()}});
tasks.delete('/groups/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const f=await family(c.env.DATABASE_URL,c.get('user').userId);const g=await db.taskGroup.findFirst({where:{id:c.req.param('id'),familyId:f??undefined}});if(!g)return c.json({error:'群組不存在'},404);await db.taskGroup.delete({where:{id:g.id}});return c.json({success:true})}finally{await db.$disconnect()}});
tasks.get('/',authenticate,async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const f=await family(c.env.DATABASE_URL,c.get('user').userId);return c.json({tasks:f?await db.task.findMany({where:{familyId:f,isActive:true},include:{group:true,createdBy:{select:{id:true,name:true}},completions:{where:{status:'PENDING'},include:{user:{select:{id:true,name:true}}}}},orderBy:[{sortOrder:'asc'},{createdAt:'asc'}]}):[]})}catch{return c.json({error:'取得任務失敗'},500)}finally{await db.$disconnect()}});
tasks.post('/',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=input.safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const f=await family(c.env.DATABASE_URL,c.get('user').userId);if(!f||!await groupOk(c.env.DATABASE_URL,f,p.data.groupId))return c.json({error:'家庭或群組無效'},400);const m=await db.task.aggregate({where:{familyId:f},_max:{sortOrder:true}});return c.json({task:await db.task.create({data:{...p.data,familyId:f,createdById:c.get('user').userId,isRecurring:p.data.isRecurring??false,keepAfterCompletion:p.data.keepAfterCompletion??true,sortOrder:(m._max.sortOrder??-1)+1}})},201)}catch{return c.json({error:'建立任務失敗'},500)}finally{await db.$disconnect()}});
tasks.post('/:id/complete',authenticate,async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const t=await db.task.findUnique({where:{id:c.req.param('id')}});if(!t||!t.isActive)return c.json({error:'任務不存在'},404);if(await family(c.env.DATABASE_URL,c.get('user').userId)!==t.familyId)return c.json({error:'無權操作此任務'},403);if(t.maxCompletions!==null&&await db.taskCompletion.count({where:{taskId:t.id,status:'APPROVED'}})>=t.maxCompletions)return c.json({error:'此任務已達完成次數上限'},400);if(await db.taskCompletion.findFirst({where:{taskId:t.id,userId:c.get('user').userId,status:'PENDING'}}))return c.json({error:'已有待審核的完成申請'},400);const body=await c.req.json().catch(()=>({}));return c.json({completion:await db.taskCompletion.create({data:{taskId:t.id,userId:c.get('user').userId,note:body.note}})},201)}finally{await db.$disconnect()}});
tasks.put('/completions/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({status:z.enum(['APPROVED','REJECTED'])}).safeParse(await c.req.json());if(!p.success)return c.json({error:'資料無效'},400);const db=createPrisma(c.env.DATABASE_URL);try{const x=await db.taskCompletion.findUnique({where:{id:c.req.param('id')},include:{task:true}});if(!x||await family(c.env.DATABASE_URL,c.get('user').userId)!==x.task.familyId)return c.json({error:'無權審核'},403);const completion=await db.$transaction(async tx=>{const claimed=await tx.taskCompletion.updateMany({where:{id:x.id,status:'PENDING'},data:{status:p.data.status,reviewedAt:new Date(),reviewedBy:c.get('user').userId}});if(!claimed.count)throw new Error('REVIEWED');if(p.data.status==='APPROVED'&&x.task.maxCompletions!==null&&await tx.taskCompletion.count({where:{taskId:x.taskId,status:'APPROVED'}})>x.task.maxCompletions)throw new Error('LIMIT');const r=await tx.taskCompletion.findUnique({where:{id:x.id}});if(p.data.status==='APPROVED'){const before=await tx.user.findUnique({where:{id:x.userId},select:{points:true}});const user=await tx.user.update({where:{id:x.userId},data:{points:{increment:x.task.points}}});await tx.pointTransaction.create({data:{userId:x.userId,amount:x.task.points,type:'EARN',reason:`完成任務：${x.task.title}`,createdBy:c.get('user').userId,balanceBefore:before?.points??0,balanceAfter:user.points}});if(!x.task.keepAfterCompletion)await tx.task.update({where:{id:x.taskId},data:{isActive:false}})}return r});if(p.data.status==='APPROVED')await evaluateTrophies(db,x.userId);return c.json({completion})}catch(e){return c.json({error:e instanceof Error&&e.message==='LIMIT'?'此任務已達完成次數上限':e instanceof Error&&e.message==='REVIEWED'?'申請已被處理':'審核失敗'},e instanceof Error&&e.message==='REVIEWED'?409:400)}finally{await db.$disconnect()}});
tasks.get('/pending',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const f=await family(c.env.DATABASE_URL,c.get('user').userId);return c.json({completions:f?await db.taskCompletion.findMany({where:{status:'PENDING',task:{familyId:f}},include:{task:true,user:{select:{id:true,name:true}}},orderBy:{completedAt:'desc'}}):[]})}finally{await db.$disconnect()}});
tasks.put('/order',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({ids:z.array(z.string()).min(1)}).safeParse(await c.req.json());if(!p.success)return c.json({error:'無效的排序資料'},400);const db=createPrisma(c.env.DATABASE_URL);try{const f=await family(c.env.DATABASE_URL,c.get('user').userId);if(!f||await db.task.count({where:{familyId:f,id:{in:p.data.ids}}})!==p.data.ids.length)return c.json({error:'無權排序此任務'},403);await db.$transaction(p.data.ids.map((id,sortOrder)=>db.task.update({where:{id},data:{sortOrder}})));return c.json({success:true})}finally{await db.$disconnect()}});
tasks.put('/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=input.partial().safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const t=await db.task.findUnique({where:{id:c.req.param('id')}});if(!t||await family(c.env.DATABASE_URL,c.get('user').userId)!==t.familyId)return c.json({error:'無權編輯此任務'},403);if(!await groupOk(c.env.DATABASE_URL,t.familyId,p.data.groupId))return c.json({error:'無效的任務群組'},400);return c.json({task:await db.task.update({where:{id:t.id},data:{...p.data,recurringType:p.data.isRecurring===false?null:p.data.recurringType}})})}finally{await db.$disconnect()}});
tasks.delete('/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const t=await db.task.findUnique({where:{id:c.req.param('id')}});if(!t||await family(c.env.DATABASE_URL,c.get('user').userId)!==t.familyId)return c.json({error:'無權刪除此任務'},403);if(await db.taskCompletion.count({where:{taskId:t.id}}))return c.json({success:true,archived:true,task:await db.task.update({where:{id:t.id},data:{isActive:false}})});await db.task.delete({where:{id:t.id}});return c.json({success:true,archived:false})}finally{await db.$disconnect()}});
export default tasks;
