import { Hono } from 'hono';
import { z } from 'zod';
import { createPrisma } from '../lib/worker-prisma';
import { authenticate, requireRoles, type WorkerRouteEnv } from './shared';

const tasks = new Hono<WorkerRouteEnv>();
async function familyId(url: string, userId: string) { const db = createPrisma(url); try { return (await db.familyMember.findFirst({ where: { userId } }))?.familyId ?? null; } finally { await db.$disconnect(); } }

tasks.get('/', authenticate, async (c) => { const db=createPrisma(c.env.DATABASE_URL); try { const fid=await familyId(c.env.DATABASE_URL,c.get('user').userId); if(!fid)return c.json({tasks:[]}); const tasks=await db.task.findMany({where:{familyId:fid,isActive:true},include:{createdBy:{select:{id:true,name:true}},completions:{where:{status:'PENDING'},include:{user:{select:{id:true,name:true}}}}},orderBy:{createdAt:'desc'}}); return c.json({tasks}); } catch(e){console.error(e);return c.json({error:'取得任務失敗'},500)} finally{await db.$disconnect()} });
tasks.post('/',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({title:z.string().min(1),description:z.string().optional(),points:z.number().int().positive(),isRecurring:z.boolean().optional(),recurringType:z.enum(['daily','weekly']).optional()}).safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const fid=await familyId(c.env.DATABASE_URL,c.get('user').userId);if(!fid)return c.json({error:'請先建立或加入家庭'},400);const task=await db.task.create({data:{familyId:fid,createdById:c.get('user').userId,...p.data,isRecurring:p.data.isRecurring??false}});return c.json({task},201)}catch(e){console.error(e);return c.json({error:'建立任務失敗'},500)}finally{await db.$disconnect()}});
tasks.post('/:id/complete',authenticate,async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const task=await db.task.findUnique({where:{id:c.req.param('id')}});if(!task||!task.isActive)return c.json({error:'任務不存在'},404);if(await familyId(c.env.DATABASE_URL,c.get('user').userId)!==task.familyId)return c.json({error:'無權操作此任務'},403);if(await db.taskCompletion.findFirst({where:{taskId:task.id,userId:c.get('user').userId,status:'PENDING'}}))return c.json({error:'已有待審核的完成申請'},400);const body=await c.req.json().catch(()=>({}));const completion=await db.taskCompletion.create({data:{taskId:task.id,userId:c.get('user').userId,note:body.note}});return c.json({completion},201)}catch(e){console.error(e);return c.json({error:'提交完成失敗'},500)}finally{await db.$disconnect()}});
tasks.put('/completions/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({status:z.enum(['APPROVED','REJECTED'])}).safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const x=await db.taskCompletion.findUnique({where:{id:c.req.param('id')},include:{task:true}});if(!x||x.status!=='PENDING')return c.json({error:'找不到待審核的完成紀錄'},404);if(await familyId(c.env.DATABASE_URL,c.get('user').userId)!==x.task.familyId)return c.json({error:'無權審核'},403);const completion=await db.$transaction(async tx=>{const result=await tx.taskCompletion.update({where:{id:x.id},data:{status:p.data.status,reviewedAt:new Date(),reviewedBy:c.get('user').userId}});if(p.data.status==='APPROVED'){await tx.user.update({where:{id:x.userId},data:{points:{increment:x.task.points}}});await tx.pointTransaction.create({data:{userId:x.userId,amount:x.task.points,type:'EARN',reason:`完成任務：${x.task.title}`,createdBy:c.get('user').userId}})}return result});return c.json({completion})}catch(e){console.error(e);return c.json({error:'審核失敗'},500)}finally{await db.$disconnect()}});
tasks.get('/pending',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const fid=await familyId(c.env.DATABASE_URL,c.get('user').userId);if(!fid)return c.json({completions:[]});const completions=await db.taskCompletion.findMany({where:{status:'PENDING',task:{familyId:fid}},include:{task:true,user:{select:{id:true,name:true}}},orderBy:{completedAt:'desc'}});return c.json({completions})}catch(e){console.error(e);return c.json({error:'取得待審核列表失敗'},500)}finally{await db.$disconnect()}});
tasks.put('/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const p=z.object({title:z.string().min(1).optional(),description:z.string().nullable().optional(),points:z.number().int().positive().optional(),isRecurring:z.boolean().optional(),recurringType:z.enum(['daily','weekly']).nullable().optional()}).safeParse(await c.req.json());if(!p.success)return c.json({error:p.error.errors[0].message},400);const db=createPrisma(c.env.DATABASE_URL);try{const task=await db.task.findUnique({where:{id:c.req.param('id')}});if(!task)return c.json({error:'任務不存在'},404);if(await familyId(c.env.DATABASE_URL,c.get('user').userId)!==task.familyId)return c.json({error:'無權編輯此任務'},403);const data={...p.data,recurringType:p.data.isRecurring===false?null:p.data.recurringType};const updated=await db.task.update({where:{id:task.id},data});return c.json({task:updated})}catch(e){console.error(e);return c.json({error:'更新任務失敗'},500)}finally{await db.$disconnect()}});
tasks.delete('/:id',authenticate,requireRoles('PARENT','ADMIN'),async c=>{const db=createPrisma(c.env.DATABASE_URL);try{const task=await db.task.findUnique({where:{id:c.req.param('id')}});if(!task)return c.json({error:'任務不存在'},404);if(await familyId(c.env.DATABASE_URL,c.get('user').userId)!==task.familyId)return c.json({error:'無權刪除此任務'},403);const count=await db.taskCompletion.count({where:{taskId:task.id}});if(count>0){const archived=await db.task.update({where:{id:task.id},data:{isActive:false}});return c.json({success:true,archived:true,task:archived})}await db.task.delete({where:{id:task.id}});return c.json({success:true,archived:false})}catch(e){console.error(e);return c.json({error:'刪除任務失敗'},500)}finally{await db.$disconnect()}});
export default tasks;
