import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Printer } from 'lucide-react';
import { api } from '../lib/api';
import { useAuth } from '../lib/auth';

function currentMonth() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`; }

export default function MonthlyReport() {
  const { user } = useAuth();
  const isParent = user?.role === 'PARENT' || user?.role === 'ADMIN';
  const [month, setMonth] = useState(currentMonth());
  const [userId, setUserId] = useState('');
  const { data, isLoading, error } = useQuery({ queryKey: ['monthlyReport', user?.id, month, userId], queryFn: () => api.getMonthlyReport(month, userId || undefined) });
  const { data: familyData } = useQuery({ queryKey: ['family',user?.id], queryFn: api.getMyFamily, enabled: isParent });
  const title = useMemo(() => `${month.replace('-', ' 年 ')} 月回顧`, [month]);

  return <div className="space-y-6"><header className="print:hidden flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-extrabold text-slate-800">每月回顧</h1><p className="mt-1 text-sm text-slate-500">自然月統計 · 不做孩子排名</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-sm font-bold">月份<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="ml-2 rounded-xl border border-slate-200 px-3 py-2 font-normal" /></label>{isParent && data && <label className="text-sm font-bold">範圍<select style={{ maxWidth: '12rem' }} value={userId} onChange={(event) => setUserId(event.target.value)} className="ml-2 rounded-xl border border-slate-200 px-3 py-2 font-normal"><option value="">家庭總覽</option>{(familyData?.family?.members.filter(m=>m.user.role==='CHILD').map(m=>m.user) ?? data.children.map(c=>c.user)).map(child=><option key={child.id} value={child.id}>{child.name}</option>)}</select></label>}<button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white"><Printer size={16} />列印報表</button></div></header>

    {isLoading ? <p role="status" className="text-slate-500">正在產生報表...</p> : error ? <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error instanceof Error ? error.message : '報表載入失敗'}</p> : data && <article className="monthly-report space-y-6 rounded-2xl bg-white p-5 sm:p-7"><div className="border-b border-slate-200 pb-4"><p className="text-sm font-bold text-primary">StarJar 家庭月報</p><h1 className="mt-1 text-2xl font-extrabold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{data.family.name} · {data.timezone}</p></div>
      {isParent && !userId && <section aria-labelledby="family-summary-title"><h2 id="family-summary-title" className="mb-3 text-lg font-extrabold">家庭總覽</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{[['獲得星星', data.familySummary.earned], ['兌換星星', data.familySummary.spent], ['扣除星星', data.familySummary.deducted], ['完成任務', data.familySummary.tasks], ['零用錢', `NT$${data.familySummary.allowanceTwd}`], ['新獎盃', data.familySummary.trophies]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-slate-50 p-3"><div className="text-xs font-bold text-slate-500">{label}</div><div className="mt-1 text-xl font-extrabold text-slate-900">{value}</div></div>)}</div></section>}
      <div className="space-y-6">{data.children.map((child) => <section key={child.user.id} className="report-child break-inside-avoid border-t border-slate-200 pt-5 first:border-0 first:pt-0"><div className="flex flex-wrap items-end justify-between gap-2"><h2 className="text-xl font-extrabold text-slate-900">{child.user.name}</h2><span className="text-sm font-bold text-slate-500">⭐ {child.summary.openingPoints} → {child.summary.closingPoints}</span></div><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-xl bg-emerald-50 p-3"><div className="text-xs font-bold text-emerald-700">本月獲得</div><div className="text-lg font-extrabold text-emerald-800">+{child.summary.earned}</div></div><div className="rounded-xl bg-blue-50 p-3"><div className="text-xs font-bold text-blue-700">獎勵／零用錢</div><div className="text-lg font-extrabold text-blue-800">-{child.summary.rewardSpent + child.summary.allowanceSpent}</div></div><div className="rounded-xl bg-amber-50 p-3"><div className="text-xs font-bold text-amber-800">扣除／補回</div><div className="text-lg font-extrabold text-amber-900">-{child.summary.deducted} / +{child.summary.reversed}</div></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><h3 className="text-sm font-extrabold text-slate-700">任務表現</h3><p className="mt-1 text-sm text-slate-600">完成 {child.taskSummary.approvedCount} 次，獲得 ⭐ {child.taskSummary.totalPoints}。</p>{child.taskSummary.topTasks.length > 0 && <p className="mt-1 text-xs text-slate-500">本月任務：{child.taskSummary.topTasks.join('、')}</p>}{child.taskSummary.rejectedCount > 0 && <p className="mt-2 text-xs text-slate-500">有 {child.taskSummary.rejectedCount} 次還可以再試一次；每一次嘗試都在累積經驗。</p>}</div><div><h3 className="text-sm font-extrabold text-slate-700">零用錢與獎盃</h3><p className="mt-1 text-sm text-slate-600">兌換零用錢 NT${child.allowanceTwd}，解鎖 {child.trophies.length} 座新獎盃。</p>{child.trophies.length > 0 && <p className="mt-1 text-xs text-slate-500">{child.trophies.map((item) => item.trophy.title).join('、')}</p>}</div></div><div className="mt-4 border-t border-slate-100 pt-3"><h3 className="text-sm font-extrabold text-slate-700">每日挑戰獎勵</h3><p className="mt-1 text-sm text-slate-600">基本任務 ⭐ {child.taskSummary.totalPoints} · 挑戰加碼 ⭐ {child.challengeSummary?.bonusStars ?? 0}</p>{child.challengeSummary?.awards.filter(a=>a.customTitle).map(a=><p key={a.id} className="mt-1 break-words text-sm text-slate-600">{a.customTitle} · {a.title}（任務日期 {a.localDate}）· {a.fulfilledAt?'已兌現':'待兌現'}</p>)}<p className="mt-1 text-xs text-slate-500">依本月實際入帳／取得統計；自訂項目不計入星星收支。</p></div></section>)}</div>
      <footer className="border-t border-slate-200 pt-4 text-xs text-slate-500">本報表由不可刪除的星星、任務、兌換及獎盃紀錄即時計算。</footer></article>}
  </div>;
}
