import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Crown, Gem, Medal, Sparkles, Trophy as TrophyIcon } from 'lucide-react';
import { api, TrophyInput } from '../lib/api';
import { useAuth } from '../lib/auth';

const tierLabels = { BRONZE: '銅星盃', SILVER: '銀星盃', GOLD: '金星盃', STELLAR: '星耀盃' };
const tierStyles = { BRONZE: 'border-orange-200 bg-orange-50 text-orange-800', SILVER: 'border-slate-300 bg-slate-100 text-slate-700', GOLD: 'border-amber-300 bg-amber-50 text-amber-800', STELLAR: 'border-violet-300 bg-violet-50 text-violet-800' };
const triggerLabels = { MANUAL: '由家長手動頒發', TASK_APPROVED_COUNT: '完成任務次數', POINTS_EARNED: '累積獲得星星', REWARD_APPROVED_COUNT: '完成兌換次數', WISH_APPROVED_COUNT: '核准願望次數' };
const empty: TrophyInput = { title: '', description: '', tier: 'BRONZE', iconKey: 'trophy', isSecret: false, triggerType: 'TASK_APPROVED_COUNT', threshold: 1 };

export default function Trophies() {
  const { user } = useAuth();
  const isParent = user?.role === 'PARENT' || user?.role === 'ADMIN';
  const qc = useQueryClient();
  const { data: familyData } = useQuery({ queryKey: ['family'], queryFn: api.getMyFamily });
  const family = familyData?.family;
  const children = family?.members.filter((member) => member.user.role === 'CHILD') ?? [];
  const isOwner = family?.ownerId === user?.id;
  const [userId, setUserId] = useState('');
  const targetUserId = isParent ? userId || children[0]?.user.id : undefined;
  const { data, isLoading } = useQuery({ queryKey: ['trophies', targetUserId], queryFn: () => api.getTrophies(targetUserId), enabled: !isParent || Boolean(targetUserId) });
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState<TrophyInput>(empty);

  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-extrabold text-slate-800"><TrophyIcon className="text-amber-500" />獎盃展示櫃</h1><p className="mt-1 text-sm text-slate-500">已解鎖的獎盃會永久保留。</p></div><div className="flex items-end gap-2">{isParent && <label className="text-sm font-bold">孩子<select value={targetUserId ?? ''} onChange={(event) => setUserId(event.target.value)} className="ml-2 rounded-xl border border-slate-200 px-3 py-2 font-normal">{children.map((member) => <option key={member.user.id} value={member.user.id}>{member.user.name}</option>)}</select></label>}{isOwner && <button type="button" onClick={() => { setForm(empty); setOpen(true); }} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">自訂獎盃</button>}</div></header>
    {isLoading ? <p role="status" className="text-slate-500">整理獎盃中...</p> : !data?.trophies.length ? <p className="text-slate-500">目前沒有獎盃。</p> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.trophies.map((trophy) => { const hidden = trophy.isSecret && !trophy.unlocked; return <article key={trophy.id} className={`relative overflow-hidden rounded-2xl border p-5 ${trophy.unlocked ? tierStyles[trophy.tier] : 'border-slate-200 bg-slate-100 text-slate-500'}`}><div className="flex items-start justify-between gap-3"><div className={`flex h-12 w-12 items-center justify-center rounded-full ${trophy.unlocked ? 'bg-white/70' : 'bg-slate-200'}`}>{trophy.tier === 'STELLAR' ? <Gem /> : trophy.tier === 'GOLD' ? <Crown /> : trophy.tier === 'SILVER' ? <Medal /> : <Sparkles />}</div><span className="text-xs font-extrabold">{tierLabels[trophy.tier]}</span></div><h2 className="mt-4 font-extrabold">{hidden ? '隱藏獎盃' : trophy.title}</h2><p className="mt-1 min-h-10 text-sm opacity-80">{hidden ? '達成條件後才會揭曉。' : trophy.description}</p><div className="mt-4"><div className="mb-1 flex justify-between text-xs font-bold"><span>{trophy.unlocked ? '已解鎖' : triggerLabels[trophy.triggerType]}</span><span>{trophy.progress}/{trophy.threshold}</span></div><div className="h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-current motion-safe:transition-all" style={{ width: `${Math.min(100, trophy.progress / trophy.threshold * 100)}%` }} /></div>{trophy.unlock?.source === 'RETROACTIVE' && <p className="mt-2 text-xs font-bold">依既有紀錄解鎖</p>}</div>{isParent && !trophy.unlocked && <button type="button" onClick={async () => { if (!targetUserId) return; await api.awardTrophy(trophy.id, targetUserId); qc.invalidateQueries({ queryKey: ['trophies', targetUserId] }); }} className="mt-4 text-sm font-extrabold text-primary">手動頒發</button>}</article>; })}</div>}

    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={async (event) => { event.preventDefault(); await api.createTrophy(form); setOpen(false); qc.invalidateQueries({ queryKey: ['trophies', targetUserId] }); }} className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6" role="dialog" aria-modal="true" aria-labelledby="trophy-form-title"><h2 id="trophy-form-title" className="text-lg font-extrabold">建立自訂獎盃</h2><label className="block text-sm font-bold">名稱<input required value={form.title} onChange={(event) => setForm((value) => ({ ...value, title: event.target.value }))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal" /></label><label className="block text-sm font-bold">說明<textarea required value={form.description} onChange={(event) => setForm((value) => ({ ...value, description: event.target.value }))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal" /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold">階級<select value={form.tier} onChange={(event) => setForm((value) => ({ ...value, tier: event.target.value as TrophyInput['tier'] }))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal">{Object.entries(tierLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-bold">解鎖方式<select value={form.triggerType} onChange={(event) => setForm((value) => ({ ...value, triggerType: event.target.value as TrophyInput['triggerType'] }))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal">{Object.entries(triggerLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>{form.triggerType !== 'MANUAL' && <label className="block text-sm font-bold">目標門檻<input type="number" min={1} value={form.threshold} onChange={(event) => setForm((value) => ({ ...value, threshold: Number(event.target.value) }))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 font-normal" /></label>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isSecret} onChange={(event) => setForm((value) => ({ ...value, isSecret: event.target.checked }))} className="h-5 w-5 accent-primary" />解鎖前隱藏名稱與條件</label><div className="flex gap-2"><button type="button" onClick={() => setOpen(false)} className="flex-1 rounded-xl bg-slate-100 py-2 font-bold">取消</button><button className="flex-1 rounded-xl bg-primary py-2 font-bold text-white">建立</button></div></form></div>}
  </div>;
}
